require "../spec_helper"

# Guards against silent catalog drift: the vendored data (regenerated by
# tasks/sync_models.cr) must stay self-consistent and keep the flagship models
# resolvable, regardless of how many models the sync task writes.
describe "LLMDB catalog drift guard" do
  it "every model has a non-empty provider id" do
    LLMDB.models.each do |model|
      model.provider.should_not be_empty
      model.id.should_not be_empty
    end
  end

  it "enumerates providers without raising" do
    providers = LLMDB.providers
    providers.should contain("openai")
    providers.should contain("anthropic")
    providers.should contain("google")
  end

  it "resolves the flagship models" do
    LLMDB.model("openai:gpt-4o-mini").id.should eq("gpt-4o-mini")
    LLMDB.model("anthropic:claude-sonnet-4-5").id.should eq("claude-sonnet-4-5")
    LLMDB.model("google:gemini-2.5-flash").id.should eq("gemini-2.5-flash")
  end

  it "keys each model consistently with its provider:id" do
    LLMDB::Catalog.all.each do |key, model|
      key.should eq(model.key)
    end
  end
end
